# The pipeline builds the docker images providing crosstool-NG.
# The different crosstool-NG versions pushed using different tags, e.g. the image
# griffinplus/toolchain-builder:ct-ng-1.24.0 contains crosstool-NG v1.24.0.

variables:
  - group: AzureKeyVault - Docker Hub
  - name: repository
    value: griffinplus/toolchain-builder
  - name: registry_user
    value: $(dockerhub-user)
  - name: registry_password
    value: $(dockerhub-password)

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - build-container/*

# do not trigger on pull requests to avoid that tag 'latest' is pushed for pull requests
pr: none

schedules:
- cron: "0 0 * * 0"
  displayName: Weekly Sunday Rebuild
  branches:
    include:
    - master
  always: true

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job:
    displayName: Build
    strategy:
      matrix:
        ct-ng-1.24.0:
          CTNG_VERSION: 1.24.0
          IMAGE_TAGS: |
            latest
            ct-ng-1.24.0
    steps:
    - task: Docker@2
      displayName: Login
      inputs:
        command: login
        containerregistry: Docker Hub
    - task: Docker@2 
      displayName: Build
      inputs:
        command: build
        Dockerfile: build-container/Dockerfile
        repository: $(repository)
        tags: $(IMAGE_TAGS)
        arguments: --build-arg CTNG_VERSION=$(CTNG_VERSION)
    - task: Docker@2 
      displayName: Push
      inputs:
        command: push
        repository: $(repository)
        tags: $(IMAGE_TAGS)
    - script: |
        set -e
        cd build-container
        docker run \
          -v $PWD:/workspace \
          -e DOCKERHUB_USERNAME='$(registry_user)' \
          -e DOCKERHUB_PASSWORD='$(registry_password)' \
          -e DOCKERHUB_REPOSITORY='$(repository)' \
          -e README_FILEPATH='/workspace/README.md' \
          griffinplus/dockerhub-description:latest
      displayName: Update Image Description
    - task: Docker@2
      displayName: Logout
      inputs:
        command: logout
        containerRegistry: Docker Hub
