# The pipeline builds the docker image, tags it as 'latest' and pushes it to the Docker Hub

variables:
  - group: AzureKeyVault - Docker Hub
  - name: repository
    value: griffinplus/toolchain-base
  - name: image_tag
    value: latest
  - name: registry_user
    value: $(dockerhub-user)
  - name: registry_password
    value: $(dockerhub-password)

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - toolchain-base-container/*

# do not trigger on pull requests to avoid that tag 'latest' is pushed for pull requests
pr: none

schedules:
- cron: "0 0 * * 0"
  displayName: Weekly Sunday Rebuild
  branches:
    include:
    - master
  always: true

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  displayName: Login
  inputs:
    command: login
    containerregistry: Docker Hub
- task: Docker@2 
  displayName: Build and Push
  inputs:
    command: buildAndPush
    Dockerfile: toolchain-base-container/Dockerfile
    repository: $(repository)
    tags: $(image_tag)
- script: |
    set -e
    cd toolchain-base-container
    docker run \
      -v $PWD:/workspace \
      -e DOCKERHUB_USERNAME='$(registry_user)' \
      -e DOCKERHUB_PASSWORD='$(registry_password)' \
      -e DOCKERHUB_REPOSITORY='$(repository)' \
      -e README_FILEPATH='/workspace/README.md' \
      griffinplus/dockerhub-description:latest
  displayName: Update Image Description
- task: Docker@2
  displayName: Logout
  inputs:
    command: logout
    containerRegistry: Docker Hub
