trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
    - toolchains/azure-pipelines-docker.yml.template
    - toolchains/configs/gcc-9.2.0/azure-pipelines-docker.yml
    - toolchains/configs/gcc-9.2.0/readme-docker.md
    - toolchains/configs/gcc-9.2.0/*.toolchain.cmake

# do not trigger on pull requests to avoid that pull requests trigger releases
pr: none

extends:
  template: ../../azure-pipelines-docker.yml.template
  parameters:
    gccVersion: 9.2.0
    dockerImage: griffinplus/toolchain-gcc-9.2.0
    readmePath: /toolchains/configs/gcc-9.2.0/readme-docker.md
